application: qrthisurl
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /(favicon\.ico)
  static_files: static/\1
  upload: static/(favicon\.ico)
  
- url: /.*
  script: qrapi.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: latest
